version: '3.9'

services:
  db:
    image: postgres:16.3-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db/:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - backend

  form_web:
    build: ./form
    env_file:
      - .env
    volumes:
      - .:/form
    ports:
      - 80:4567
    depends_on:
      db:
        condition: service_healthy
    networks:
      - frontend
      - backend

  list_web:
    build: ./list
    env_file:
      - .env
    volumes:
      - .:/list
    ports:
      - 81:4567
    depends_on:
      db:
        condition: service_healthy
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db:
    driver: local

